{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "523816ae-397a-4da5-8816-d3ab6d8d8305",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Median: 11.0\n"
     ]
    }
   ],
   "source": [
    "from typing import List\n",
    "def find_median_sorted_arrays(nums1,nums2):\n",
    "    #Always ensure binary search runs on the smaller array for 0(log(min(m,n)))\n",
    "    if len(nums1) >len(nums2):\n",
    "        nums1,nums2 =nums2,nums1\n",
    "    m, n =len(nums1),len(nums2)\n",
    "    low,high =0,m\n",
    "    while low<=high:\n",
    "        partition_x =(low +high)//2\n",
    "        partition_y = (m+n+1)//2 -partition_x\n",
    "        # Edge cases: Agar partition extreme left/right par ho\n",
    "        max_left_x = float('-inf') if partition_x == 0 else nums1[partition_x - 1]\n",
    "        min_right_x = float('inf') if partition_x == m else nums1[partition_x]\n",
    "\n",
    "        max_left_y = float('-inf') if partition_y == 0 else nums2[partition_y - 1]\n",
    "        min_right_y = float('inf') if partition_y == n else nums2[partition_y]\n",
    "\n",
    "        # Valid Partition Condition Check\n",
    "        if max_left_x <= min_right_y and max_left_y <= min_right_x:\n",
    "            # Odd total length\n",
    "            if (m + n) % 2 != 0:\n",
    "                return float(max(max_left_x, max_left_y))\n",
    "            # Even total length\n",
    "            return (max(max_left_x, max_left_y) + min(min_right_x, min_right_y)) / 2.0\n",
    "        \n",
    "        elif max_left_x > min_right_y:\n",
    "            # Left side mein heavy elements hain, move search space to left\n",
    "            high = partition_x - 1\n",
    "        else:\n",
    "            # Left side mein kam elements hain, move search space to right\n",
    "            low = partition_x + 1\n",
    "\n",
    "    raise ValueError(\"Input arrays are not sorted properly.\")\n",
    "\n",
    "\n",
    "# --- Test Drive ---\n",
    "arr1 = [1, 3, 8, 9, 15]\n",
    "arr2 = [7, 11, 18, 19, 21, 25]\n",
    "print(f\"Median: {find_median_sorted_arrays(arr1, arr2)}\")  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7e6be242-2ecb-4718-a78f-43823e08a7d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Minimum Ship Capacity Required: 15\n"
     ]
    }
   ],
   "source": [
    "def ship_within_days(weights, days):\n",
    "    # Helper function: Check if a given capacity can ship all packages in 'days'\n",
    "    def can_ship(capacity):\n",
    "        current_days = 1\n",
    "        current_load = 0\n",
    "        \n",
    "        for w in weights:\n",
    "            if current_load + w > capacity:\n",
    "                current_days += 1\n",
    "                current_load = w\n",
    "            else:\n",
    "                current_load += w\n",
    "                \n",
    "        return current_days <= days\n",
    "\n",
    "    # Binary search bounds on the answer space\n",
    "    low = max(weights)    # Sabse bada single package (is-se kam capacity nahi ho sakti)\n",
    "    high = sum(weights)   # Saare packages ka total weight (sab ek din mein bhej do)\n",
    "    ans = high\n",
    "\n",
    "    while low <= high:\n",
    "        mid = (low + high) // 2\n",
    "        \n",
    "        if can_ship(mid):\n",
    "            ans = mid\n",
    "            high = mid - 1  # Aur choti capacity try karo\n",
    "        else:\n",
    "            low = mid + 1   # Capacity kam pad gayi, badhao\n",
    "\n",
    "    return ans\n",
    "\n",
    "\n",
    "# --- Test Run ---\n",
    "package_weights = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n",
    "d = 5\n",
    "\n",
    "min_capacity = ship_within_days(package_weights, d)\n",
    "print(f\"Minimum Ship Capacity Required: {min_capacity}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "b296043c-a6f6-440c-9e24-3c6eb93f6e5e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Added Transaction #1: Food - ₹1200.5\n",
      "Added Transaction #2: Books - ₹4500.0\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'trans_id': 2,\n",
       " 'category': 'Books',\n",
       " 'amount': 4500.0,\n",
       " 'date': '2026-07-28',\n",
       " 'description': 'Geo-AI & Python Textbooks'}"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import csv\n",
    "import json\n",
    "from datetime import datetime\n",
    "class PersonalFinanceEngine:\n",
    "    def __init__(self,monthly_budget=50000.0):\n",
    "        self.monthly_budget =float(monthly_budget)\n",
    "        self. transactions =[]\n",
    "        self._next_id =1\n",
    "    def add_transaction(self,category,amount,description):\n",
    "        if amount<= 0:\n",
    "            print(f\"Error:Amount (₹{amount}) positive hona chahiye.\")\n",
    "            return None\n",
    "        tx = {\n",
    "         \"trans_id\": self._next_id,\n",
    "         \"category\": category.strip().capitalize(),\n",
    "         \"amount\": float(amount),\n",
    "         \"date\": datetime.now().strftime(\"%Y-%m-%d\"),\n",
    "         \"description\": description.strip()\n",
    "         }\n",
    "        self.transactions.append(tx)\n",
    "        self._next_id += 1\n",
    "        print(f\"Added Transaction #{tx['trans_id']}: {tx['category']} - ₹{tx['amount']}\")\n",
    "        return tx\n",
    "\n",
    "\n",
    "# --- Step 1 Test ---\n",
    "engine = PersonalFinanceEngine(monthly_budget=25000.00)\n",
    "engine.add_transaction(\"Food\", 1200.50, \"Canteen & Groceries\")\n",
    "engine.add_transaction(\"Books\", 4500.00, \"Geo-AI & Python Textbooks\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "e4949567-b764-478a-ad3c-2846acbffd94",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'PersonalFinanceEngine' object has no attribute 'get_summary'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[22]\u001b[39m\u001b[32m, line 29\u001b[39m\n\u001b[32m     25\u001b[39m         print(f\"Status         : {status}\")\n\u001b[32m     26\u001b[39m         print(\u001b[33m\"-----------------------------\\n\"\u001b[39m)\n\u001b[32m     27\u001b[39m \n\u001b[32m     28\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m summary\n\u001b[32m---> \u001b[39m\u001b[32m29\u001b[39m engine.get_summary()\n",
      "\u001b[31mAttributeError\u001b[39m: 'PersonalFinanceEngine' object has no attribute 'get_summary'"
     ]
    }
   ],
   "source": [
    "def get_summary(self):\n",
    "    #1. Saare transactions ka total expense calculate karo\n",
    "    total_spent =sum(tx[\"amount\"] for tx in self.transactions)\n",
    "    #2. Remaining balance nikalo\n",
    "    remaining_budget= self.monthly_budget-total_spent\n",
    "    #3.Status message set karo\n",
    "    if remaining_budget <0:\n",
    "        status = f\"WARNING:Budget exceeded by₹{abs(remaining_budget):.2f}!\"\n",
    "    else:\n",
    "        status =f\" Within Budget.${remaining_budget:.2f}remaining.\"\n",
    "   # 4. Summary Dictionary return karo\n",
    "        summary = {\n",
    "            \"monthly_budget\": self.monthly_budget,\n",
    "            \"total_spent\": total_spent,\n",
    "            \"remaining_budget\": remaining_budget,\n",
    "            \"total_transactions\": len(self.transactions),\n",
    "            \"status\": status\n",
    "        }\n",
    "        \n",
    "        # Screen par print karke dikhao\n",
    "        print(\"\\n--- 📊 FINANCIAL SUMMARY ---\")\n",
    "        print(f\"Monthly Budget : ₹{self.monthly_budget:.2f}\")\n",
    "        print(f\"Total Spent    : ₹{total_spent:.2f}\")\n",
    "        print(f\"Remaining      : ₹{remaining_budget:.2f}\")\n",
    "        print(f\"Status         : {status}\")\n",
    "        print(\"-----------------------------\\n\")\n",
    "        \n",
    "        return summary \n",
    "engine.get_summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "49939338-6484-4c3e-936b-908dc4c30ed8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== INITIALIZING AUTOMATED PERSONAL FINANCE ENGINE ===\n",
      "\n",
      "Added Transaction #1: Food - ₹1200.5\n",
      "Budget Status: Spent ₹1200.50 | Remaining ₹23799.50\n",
      "Added Transaction #2: Books - ₹4500.0\n",
      "Budget Status: Spent ₹5700.50 | Remaining ₹19299.50\n",
      "Added Transaction #3: Travel - ₹8000.0\n",
      "Budget Status: Spent ₹13700.50 | Remaining ₹11299.50\n",
      "Added Transaction #4: Electronics - ₹15000.0\n",
      "ALERT: Budget Exceeded! Limit: ₹25000.00, Spent: ₹28700.50, Over by: ₹3700.50\n",
      "\n",
      "--- CATEGORY FILTER (Food) ---\n",
      "[{'trans_id': 1, 'category': 'Food', 'amount': 1200.5, 'date': '2026-07-28', 'description': 'Canteen & Groceries'}]\n",
      "\n",
      "--- SORTED BY AMOUNT (DESCENDING) ---\n",
      "₹15000.00 -> Electronics (GPU Cooling Pad)\n",
      "₹8000.00 -> Travel (Flight tickets)\n",
      "₹4500.00 -> Books (Geo-AI & Python Textbooks)\n",
      "₹1200.50 -> Food (Canteen & Groceries)\n",
      "\n",
      "--- EXPORTING FILES ---\n",
      "Successfully exported JSON summary to 'finance_summary.json'\n",
      "Successfully exported CSV report to 'transactions.csv'\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "import json\n",
    "import logging\n",
    "from datetime import datetime\n",
    "\n",
    "# Logging setup for enterprise tracing\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s [%(levelname)s] %(message)s\"\n",
    ")\n",
    "\n",
    "class PersonalFinanceEngine:\n",
    "    def __init__(self, monthly_budget=50000.0):\n",
    "        self.monthly_budget = float(monthly_budget)\n",
    "        self.transactions = []\n",
    "        self._next_id = 1\n",
    "\n",
    "    def add_transaction(self, category, amount, description):\n",
    "        \"\"\"Validates and records a new transaction.\"\"\"\n",
    "        if amount <= 0:\n",
    "            print(f\"Error: Transaction amount (₹{amount}) must be greater than 0.\")\n",
    "            return None\n",
    "        \n",
    "        tx = {\n",
    "            \"trans_id\": self._next_id,\n",
    "            \"category\": category.strip().capitalize(),\n",
    "            \"amount\": float(amount),\n",
    "            \"date\": datetime.now().strftime(\"%Y-%m-%d\"),\n",
    "            \"description\": description.strip()\n",
    "        }\n",
    "        self.transactions.append(tx)\n",
    "        self._next_id += 1\n",
    "\n",
    "        print(f\"Added Transaction #{tx['trans_id']}: {tx['category']} - ₹{tx['amount']}\")\n",
    "        self.check_budget_status()\n",
    "        return tx\n",
    "\n",
    "    def get_total_expenses(self):\n",
    "        \"\"\"Calculates total spend.\"\"\"\n",
    "        return sum(tx[\"amount\"] for tx in self.transactions)\n",
    "\n",
    "    def check_budget_status(self):\n",
    "        \"\"\"Monitors current budget health.\"\"\"\n",
    "        total_spend = self.get_total_expenses()\n",
    "        remaining = self.monthly_budget - total_spend\n",
    "\n",
    "        if total_spend > self.monthly_budget:\n",
    "            print(f\"ALERT: Budget Exceeded! Limit: ₹{self.monthly_budget:.2f}, Spent: ₹{total_spend:.2f}, Over by: ₹{abs(remaining):.2f}\")\n",
    "        else:\n",
    "            print(f\"Budget Status: Spent ₹{total_spend:.2f} | Remaining ₹{remaining:.2f}\")\n",
    "\n",
    "    def filter_by_category(self, category):\n",
    "        \"\"\"Filters transactions based on category.\"\"\"\n",
    "        cat_clean = category.strip().capitalize()\n",
    "        return [tx for tx in self.transactions if tx[\"category\"] == cat_clean]\n",
    "\n",
    "    def sort_transactions_by_amount(self, descending=True):\n",
    "        \"\"\"Sorts transactions using O(n log n) Timsort.\"\"\"\n",
    "        return sorted(self.transactions, key=lambda tx: tx[\"amount\"], reverse=descending)\n",
    "\n",
    "    def export_summary_json(self, filepath=\"finance_summary.json\"):\n",
    "        \"\"\"Exports summary data to a JSON file.\"\"\"\n",
    "        try:\n",
    "            summary_data = {\n",
    "                \"generated_at\": datetime.now().isoformat(),\n",
    "                \"monthly_budget\": self.monthly_budget,\n",
    "                \"total_expenses\": self.get_total_expenses(),\n",
    "                \"remaining_budget\": self.monthly_budget - self.get_total_expenses(),\n",
    "                \"transaction_count\": len(self.transactions),\n",
    "                \"transactions\": self.transactions\n",
    "            }\n",
    "            with open(filepath, \"w\") as f:\n",
    "                json.dump(summary_data, f, indent=4)\n",
    "            print(f\"Successfully exported JSON summary to '{filepath}'\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error exporting JSON: {e}\")\n",
    "            return False\n",
    "\n",
    "    def export_csv_report(self, filepath=\"transactions.csv\"):\n",
    "        \"\"\"Exports transaction ledger to a CSV file.\"\"\"\n",
    "        try:\n",
    "            with open(filepath, \"w\", newline=\"\") as f:\n",
    "                writer = csv.writer(f)\n",
    "                writer.writerow([\"ID\", \"Category\", \"Amount\", \"Date\", \"Description\"])\n",
    "                for tx in self.transactions:\n",
    "                    writer.writerow([tx[\"trans_id\"], tx[\"category\"], tx[\"amount\"], tx[\"date\"], tx[\"description\"]])\n",
    "            print(f\"Successfully exported CSV report to '{filepath}'\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error exporting CSV: {e}\")\n",
    "            return False\n",
    "\n",
    "\n",
    "# --- Test Drive ---\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"\\n=== INITIALIZING AUTOMATED PERSONAL FINANCE ENGINE ===\\n\")\n",
    "    engine = PersonalFinanceEngine(monthly_budget=25000.00)\n",
    "\n",
    "    # Adding sample transactions\n",
    "    engine.add_transaction(\"Food\", 1200.50, \"Canteen & Groceries\")\n",
    "    engine.add_transaction(\"Books\", 4500.00, \"Geo-AI & Python Textbooks\")\n",
    "    engine.add_transaction(\"Travel\", 8000.00, \"Flight tickets\")\n",
    "    engine.add_transaction(\"Electronics\", 15000.00, \"GPU Cooling Pad\")  # Budget overload test\n",
    "\n",
    "    print(\"\\n--- CATEGORY FILTER (Food) ---\")\n",
    "    print(engine.filter_by_category(\"food\"))\n",
    "\n",
    "    print(\"\\n--- SORTED BY AMOUNT (DESCENDING) ---\")\n",
    "    for tx in engine.sort_transactions_by_amount():\n",
    "        print(f\"₹{tx['amount']:.2f} -> {tx['category']} ({tx['description']})\")\n",
    "\n",
    "    print(\"\\n--- EXPORTING FILES ---\")\n",
    "    engine.export_summary_json()\n",
    "    engine.export_csv_report()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4ee23f0b-ef17-4f47-a0e8-1c98fe9a15ac",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
